SELECT
    c.NAME,
    'R'||to_char(NVL(SUM(o.QUANTITY * p.PRICE), 0),'FM999,999,999.00') AS TOTAL_SUM_SPEND
FROM
    CUSTOMERS c
LEFT JOIN ORDERS o
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
LEFT JOIN PRODUCTS p
    ON o.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    c.NAME
ORDER BY
    NVL(SUM(o.QUANTITY * p.PRICE), 0) DESC
FETCH FIRST 3 ROWS ONLY;
